/**
 * scripts/generate-quiz-content.ts
 * Content ingestion script for quiz questions.
 * Gathers educational quiz questions from curated sources and converts them
 * into schema v1 content pack format.
 *
 * Run with: npx tsx scripts/generate-quiz-content.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

import type {
  QuizQuestionPack,
  QuizShard,
  QuizCategory,
  QuizDifficulty,
  AgeBand,
} from '../src/types/content-pack.types';
import {
  SCHEMA_VERSION,
  MAX_QUESTIONS_PER_SHARD,
  createAgeMetadata,
  createProvenanceMetadata,
} from '../src/types/content-pack.types';

// ─── Curated Quiz Questions ─────────────────────────────────

interface RawQuizQuestion {
  question: string;
  answers: string[];
  correctIndex: number;
  category: QuizCategory;
  difficulty: QuizDifficulty;
  ageBand: AgeBand;
  hint: string;
  explanation?: string;
  tags?: string[];
  source: string;
  sourceUrl?: string;
}

/**
 * Manually curated quiz questions from public domain and educational resources.
 * Sources include:
 * - Public domain trivia questions
 * - Educational websites (Games4ESL, Just Family Fun, etc.)
 * - Manual curation following educational standards
 */
const CURATED_QUESTIONS: RawQuizQuestion[] = [
  // ──── Math Questions (Easy - Ages 5-7) ────
  {
    question: 'What is 5 + 3?',
    answers: ['8', '7', '9', '6'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Count on your fingers!',
    explanation: '5 + 3 = 8. Try counting 5 fingers, then add 3 more.',
    tags: ['addition', 'counting'],
    source: 'manual-curation',
  },
  {
    question: 'What is 10 - 4?',
    answers: ['6', '5', '7', '4'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Start at 10 and count back 4.',
    explanation: '10 - 4 = 6. If you have 10 apples and eat 4, you have 6 left.',
    tags: ['subtraction', 'counting'],
    source: 'manual-curation',
  },
  {
    question: 'What is 2 × 3?',
    answers: ['6', '5', '8', '4'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Think of 2 groups of 3.',
    explanation: '2 × 3 = 6. Two groups of three items equals six items total.',
    tags: ['multiplication', 'groups'],
    source: 'manual-curation',
  },
  {
    question: 'What shape has 3 sides?',
    answers: ['Triangle', 'Square', 'Circle', 'Rectangle'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Count the sides of each shape.',
    explanation: 'A triangle has exactly 3 sides and 3 corners.',
    tags: ['geometry', 'shapes'],
    source: 'manual-curation',
  },
  {
    question: 'How many sides does a square have?',
    answers: ['4', '3', '5', '6'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Look at a dice!',
    explanation: 'A square has 4 equal sides.',
    tags: ['geometry', 'shapes'],
    source: 'manual-curation',
  },

  // ──── Math Questions (Medium - Ages 8-10) ────
  {
    question: 'What is 12 × 8?',
    answers: ['96', '84', '104', '88'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Think of 12 × 10, then subtract 12 × 2.',
    explanation: '12 × 8 = 96. You can break it down: (12 × 10) - (12 × 2) = 120 - 24 = 96.',
    tags: ['multiplication', 'mental-math'],
    source: 'manual-curation',
  },
  {
    question: 'What is 1/2 + 1/4?',
    answers: ['3/4', '1/3', '2/6', '1/2'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Convert 1/2 to quarters first.',
    explanation: '1/2 = 2/4, so 2/4 + 1/4 = 3/4.',
    tags: ['fractions', 'addition'],
    source: 'manual-curation',
  },
  {
    question: 'What is the perimeter of a rectangle with length 6 and width 4?',
    answers: ['20', '24', '10', '18'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Add all four sides: length + length + width + width.',
    explanation: 'Perimeter = 2 × (length + width) = 2 × (6 + 4) = 2 × 10 = 20.',
    tags: ['geometry', 'perimeter'],
    source: 'manual-curation',
  },
  {
    question: 'What is 144 ÷ 12?',
    answers: ['12', '11', '13', '14'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: '12 times what number equals 144?',
    explanation: '144 ÷ 12 = 12. This is the same as asking: 12 × ? = 144.',
    tags: ['division', 'times-tables'],
    source: 'manual-curation',
  },
  {
    question: 'What is 25% of 80?',
    answers: ['20', '15', '25', '30'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: '25% is the same as 1/4.',
    explanation: '25% of 80 = 1/4 × 80 = 20.',
    tags: ['percentage', 'fractions'],
    source: 'manual-curation',
  },

  // ──── Math Questions (Hard - Ages 11-12+) ────
  {
    question: 'What is the value of π (pi) to 2 decimal places?',
    answers: ['3.14', '3.41', '3.12', '3.24'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It starts with 3.14...',
    explanation: 'π (pi) is approximately 3.14159, which rounds to 3.14.',
    tags: ['geometry', 'constants', 'circles'],
    source: 'public-domain',
  },
  {
    question: 'What is the square root of 169?',
    answers: ['13', '12', '14', '15'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Which number times itself equals 169?',
    explanation: '√169 = 13, because 13 × 13 = 169.',
    tags: ['square-roots', 'algebra'],
    source: 'manual-curation',
  },
  {
    question: 'If a train travels 120 miles in 2 hours, what is its average speed?',
    answers: ['60 mph', '50 mph', '70 mph', '55 mph'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Speed = Distance ÷ Time.',
    explanation: 'Average speed = 120 miles ÷ 2 hours = 60 miles per hour.',
    tags: ['word-problems', 'rate', 'distance'],
    source: 'manual-curation',
  },
  {
    question: 'What is 7² + 3²?',
    answers: ['58', '52', '60', '49'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: '7² = 49 and 3² = 9.',
    explanation: '7² = 49, 3² = 9, so 49 + 9 = 58.',
    tags: ['exponents', 'squares'],
    source: 'manual-curation',
  },
  {
    question: 'Solve for x: 2x + 5 = 17',
    answers: ['6', '5', '7', '8'],
    correctIndex: 0,
    category: 'math',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Subtract 5 from both sides first.',
    explanation: '2x + 5 = 17 → 2x = 12 → x = 6.',
    tags: ['algebra', 'equations'],
    source: 'manual-curation',
  },

  // ──── Science Questions (Easy - Ages 5-7) ────
  {
    question: 'What color is the sky on a clear day?',
    answers: ['Blue', 'Green', 'Red', 'Yellow'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Look outside!',
    explanation: 'The sky appears blue because of how sunlight scatters in the atmosphere.',
    tags: ['observation', 'nature'],
    source: 'manual-curation',
  },
  {
    question: 'How many legs does a dog have?',
    answers: ['4', '2', '6', '8'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Count them!',
    explanation: 'Dogs, cats, and most mammals have 4 legs.',
    tags: ['animals', 'biology'],
    source: 'manual-curation',
  },
  {
    question: 'What do plants need to grow?',
    answers: ['Water and sunlight', 'Only water', 'Only sunlight', 'Nothing'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Plants are living things!',
    explanation: 'Plants need water, sunlight, air, and nutrients from soil to grow.',
    tags: ['plants', 'biology'],
    source: 'manual-curation',
  },
  {
    question: 'What season comes after winter?',
    answers: ['Spring', 'Summer', 'Fall', 'Winter'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Flowers start blooming!',
    explanation: 'Spring comes after winter, when flowers bloom and it gets warmer.',
    tags: ['seasons', 'earth-science'],
    source: 'manual-curation',
  },
  {
    question: 'Which animal lays eggs?',
    answers: ['Chicken', 'Dog', 'Cat', 'Cow'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Think about breakfast!',
    explanation: 'Chickens and many birds lay eggs. Mammals like dogs and cats give live birth.',
    tags: ['animals', 'biology'],
    source: 'manual-curation',
  },

  // ──── Science Questions (Medium - Ages 8-10) ────
  {
    question: 'What is the chemical symbol for water?',
    answers: ['H₂O', 'CO₂', 'O₂', 'NaCl'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Two hydrogen atoms and one oxygen atom.',
    explanation: 'Water is H₂O: two hydrogen (H) atoms bonded to one oxygen (O) atom.',
    tags: ['chemistry', 'molecules'],
    source: 'public-domain',
    sourceUrl: 'https://en.wikipedia.org/wiki/Water',
  },
  {
    question: 'What organ pumps blood through your body?',
    answers: ['Heart', 'Lungs', 'Brain', 'Stomach'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It beats about 100,000 times per day.',
    explanation: 'The heart is a muscle that pumps blood throughout your body.',
    tags: ['anatomy', 'biology'],
    source: 'manual-curation',
  },
  {
    question: 'What planet is known as the "Red Planet"?',
    answers: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It looks red because of rust on its surface.',
    explanation: 'Mars appears red because its surface contains iron oxide (rust).',
    tags: ['astronomy', 'planets'],
    source: 'public-domain',
  },
  {
    question: 'What is the process by which plants make their own food?',
    answers: ['Photosynthesis', 'Respiration', 'Digestion', 'Evaporation'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Plants use sunlight for this process.',
    explanation: 'Photosynthesis is how plants convert sunlight, water, and CO₂ into food (glucose) and oxygen.',
    tags: ['biology', 'plants'],
    source: 'manual-curation',
  },
  {
    question: 'What is the hardest natural substance on Earth?',
    answers: ['Diamond', 'Iron', 'Quartz', 'Gold'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It\'s made of carbon and sparkles!',
    explanation: 'Diamond is the hardest natural substance. It forms deep underground under extreme pressure.',
    tags: ['geology', 'minerals'],
    source: 'public-domain',
  },

  // ──── Science Questions (Hard - Ages 11-12+) ────
  {
    question: 'What is the speed of light in a vacuum?',
    answers: ['300,000 km/s', '150,000 km/s', '500,000 km/s', '1,000,000 km/s'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It takes about 8 minutes for light to reach Earth from the Sun.',
    explanation: 'Light travels at approximately 300,000 kilometers per second (299,792 km/s to be precise).',
    tags: ['physics', 'light'],
    source: 'public-domain',
  },
  {
    question: 'What is the smallest unit of matter?',
    answers: ['Atom', 'Molecule', 'Cell', 'Proton'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Everything is made of these tiny particles.',
    explanation: 'An atom is the smallest unit of matter that retains the properties of an element.',
    tags: ['chemistry', 'matter'],
    source: 'public-domain',
  },
  {
    question: 'How many bones does an adult human have?',
    answers: ['206', '300', '150', '250'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Babies actually have more bones!',
    explanation: 'Adults have 206 bones. Babies are born with about 300 bones, but many fuse together as they grow.',
    tags: ['anatomy', 'biology'],
    source: 'public-domain',
  },
  {
    question: 'What gas makes up about 78% of Earth\'s atmosphere?',
    answers: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Helium'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s not the gas we breathe!',
    explanation: 'Nitrogen makes up about 78% of Earth\'s atmosphere, while oxygen is about 21%.',
    tags: ['earth-science', 'atmosphere'],
    source: 'public-domain',
  },
  {
    question: 'What force keeps planets in orbit around the Sun?',
    answers: ['Gravity', 'Magnetism', 'Friction', 'Inertia'],
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Isaac Newton discovered the laws of this force.',
    explanation: 'Gravity is the force that attracts objects with mass toward each other. The Sun\'s gravity keeps planets in orbit.',
    tags: ['physics', 'astronomy'],
    source: 'public-domain',
  },

  // ──── History Questions (Easy - Ages 5-7) ────
  {
    question: 'What is the capital of the United States?',
    answers: ['Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It\'s named after the first president!',
    explanation: 'Washington, D.C. is the capital city of the United States.',
    tags: ['geography', 'capitals'],
    source: 'public-domain',
  },
  {
    question: 'What animal is featured on the United States flag along with stars?',
    answers: ['No animal', 'Eagle', 'Lion', 'Bear'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'The flag has stars and stripes!',
    explanation: 'The US flag has 50 stars and 13 stripes, but no animals.',
    tags: ['symbols', 'flags'],
    source: 'manual-curation',
  },
  {
    question: 'Who was the first president of the United States?',
    answers: ['George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'Benjamin Franklin'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'The capital city is named after him!',
    explanation: 'George Washington was the first president of the United States (1789-1797).',
    tags: ['presidents', 'american-history'],
    source: 'public-domain',
  },
  {
    question: 'Which holiday celebrates the birth of the United States?',
    answers: ['Independence Day (July 4th)', 'Thanksgiving', 'Memorial Day', 'Presidents Day'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It\'s in the summer with fireworks!',
    explanation: 'July 4th (Independence Day) celebrates when the United States declared independence in 1776.',
    tags: ['holidays', 'american-history'],
    source: 'public-domain',
  },
  {
    question: 'What did people ride in before cars were invented?',
    answers: ['Horse and carriage', 'Bicycle', 'Train', 'Airplane'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Think of old cowboy movies!',
    explanation: 'Before cars, people commonly traveled by horse and carriage.',
    tags: ['transportation', 'technology'],
    source: 'manual-curation',
  },

  // ──── History Questions (Medium - Ages 8-10) ────
  {
    question: 'What year did World War II end?',
    answers: ['1945', '1943', '1947', '1941'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'The 1940s, closer to the middle.',
    explanation: 'World War II ended in 1945 with Germany surrendering in May and Japan in September.',
    tags: ['world-war-2', '20th-century'],
    source: 'public-domain',
  },
  {
    question: 'Which ancient civilization built the pyramids?',
    answers: ['Ancient Egypt', 'Ancient Greece', 'Ancient Rome', 'Ancient China'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Think of the Nile River!',
    explanation: 'The ancient Egyptians built the pyramids as tombs for their pharaohs.',
    tags: ['ancient-civilizations', 'egypt'],
    source: 'public-domain',
  },
  {
    question: 'Who was the first person to walk on the Moon?',
    answers: ['Neil Armstrong', 'Buzz Aldrin', 'John Glenn', 'Yuri Gagarin'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: '"That\'s one small step for man..."',
    explanation: 'Neil Armstrong walked on the Moon on July 20, 1969, during the Apollo 11 mission.',
    tags: ['space', 'exploration'],
    source: 'public-domain',
  },
  {
    question: 'What year did the Titanic sink?',
    answers: ['1912', '1915', '1905', '1920'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Early 1900s, before World War I.',
    explanation: 'The Titanic sank on April 15, 1912, after hitting an iceberg.',
    tags: ['20th-century', 'disasters'],
    source: 'public-domain',
  },
  {
    question: 'Which ancient structure was built in Rome for gladiator fights?',
    answers: ['The Colosseum', 'The Parthenon', 'The Pyramids', 'Stonehenge'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It\'s a large arena in Italy.',
    explanation: 'The Colosseum in Rome was used for gladiator contests and public spectacles.',
    tags: ['ancient-rome', 'architecture'],
    source: 'public-domain',
  },

  // ──── History Questions (Hard - Ages 11-12+) ────
  {
    question: 'Who invented the printing press?',
    answers: ['Johannes Gutenberg', 'Leonardo da Vinci', 'Isaac Newton', 'Benjamin Franklin'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'A German inventor in the 1400s.',
    explanation: 'Johannes Gutenberg invented the printing press around 1440, revolutionizing communication.',
    tags: ['inventions', 'renaissance'],
    source: 'public-domain',
  },
  {
    question: 'What year did Christopher Columbus first reach the Americas?',
    answers: ['1492', '1500', '1485', '1510'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Remember: "In fourteen hundred ninety-two..."',
    explanation: 'Columbus reached the Caribbean in 1492, though he thought he had reached Asia.',
    tags: ['exploration', 'americas'],
    source: 'public-domain',
  },
  {
    question: 'Who was Tutankhamun?',
    answers: ['An Egyptian pharaoh', 'A Greek philosopher', 'A Roman emperor', 'A Chinese emperor'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Also known as King Tut.',
    explanation: 'Tutankhamun was a young Egyptian pharaoh whose tomb was discovered almost intact in 1922.',
    tags: ['ancient-egypt', 'archaeology'],
    source: 'public-domain',
  },
  {
    question: 'What was the name of the ship that brought the Pilgrims to America?',
    answers: ['Mayflower', 'Santa Maria', 'Beagle', 'Victory'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s named after a flower.',
    explanation: 'The Mayflower brought the Pilgrims to Plymouth, Massachusetts in 1620.',
    tags: ['american-history', 'colonial'],
    source: 'public-domain',
  },
  {
    question: 'Who wrote the Declaration of Independence?',
    answers: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'],
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'He was the 3rd president of the United States.',
    explanation: 'Thomas Jefferson was the primary author of the Declaration of Independence in 1776.',
    tags: ['american-history', 'founding-fathers'],
    source: 'public-domain',
  },

  // ──── Language Questions (Easy - Ages 5-7) ────
  {
    question: 'How many letters are in the English alphabet?',
    answers: ['26', '24', '28', '20'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Count from A to Z!',
    explanation: 'The English alphabet has 26 letters, from A to Z.',
    tags: ['alphabet', 'basics'],
    source: 'manual-curation',
  },
  {
    question: 'Which word is a color: run, blue, happy, quickly?',
    answers: ['blue', 'run', 'happy', 'quickly'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Think of the sky!',
    explanation: 'Blue is a color. Run is a verb, happy is an adjective, and quickly is an adverb.',
    tags: ['vocabulary', 'colors'],
    source: 'manual-curation',
  },
  {
    question: 'What is the opposite of "hot"?',
    answers: ['Cold', 'Warm', 'Cool', 'Freezing'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Think of ice!',
    explanation: 'Cold is the opposite of hot. They are antonyms.',
    tags: ['opposites', 'vocabulary'],
    source: 'manual-curation',
  },
  {
    question: 'Which word rhymes with "cat"?',
    answers: ['hat', 'dog', 'car', 'cup'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Listen to the ending sound!',
    explanation: 'Hat rhymes with cat. They both end with the "at" sound.',
    tags: ['rhyming', 'phonics'],
    source: 'manual-curation',
  },
  {
    question: 'What letter does the word "apple" start with?',
    answers: ['A', 'B', 'C', 'D'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It\'s the first letter of the alphabet!',
    explanation: 'Apple starts with the letter A.',
    tags: ['alphabet', 'spelling'],
    source: 'manual-curation',
  },

  // ──── Language Questions (Medium - Ages 8-10) ────
  {
    question: 'What is the plural of "child"?',
    answers: ['children', 'childs', 'childes', 'childrens'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'This is an irregular plural!',
    explanation: 'The plural of child is children. It doesn\'t follow the regular "add -s" rule.',
    tags: ['grammar', 'plurals'],
    source: 'manual-curation',
  },
  {
    question: 'What does the prefix "pre-" mean?',
    answers: ['before', 'after', 'during', 'against'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Think of "preview" - seeing something before.',
    explanation: 'The prefix "pre-" means before. Preview, preheat, prehistoric all mean before something.',
    tags: ['prefixes', 'vocabulary'],
    source: 'manual-curation',
  },
  {
    question: 'Which sentence is correct?',
    answers: ['She and I went to the store.', 'Me and her went to the store.', 'Her and me went to the store.', 'I and she went to the store.'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Use "I" when you\'re the subject!',
    explanation: 'The correct form is "She and I" because they are the subjects doing the action.',
    tags: ['grammar', 'pronouns'],
    source: 'manual-curation',
  },
  {
    question: 'What is a synonym for "happy"?',
    answers: ['joyful', 'sad', 'angry', 'tired'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'A synonym means the same thing.',
    explanation: 'Joyful is a synonym for happy - they both mean feeling good or pleased.',
    tags: ['synonyms', 'vocabulary'],
    source: 'manual-curation',
  },
  {
    question: 'Which word is a noun: run, quickly, beautiful, dog?',
    answers: ['dog', 'run', 'quickly', 'beautiful'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'A noun is a person, place, or thing.',
    explanation: 'Dog is a noun (a thing). Run is a verb, quickly is an adverb, beautiful is an adjective.',
    tags: ['grammar', 'parts-of-speech'],
    source: 'manual-curation',
  },

  // ──── Language Questions (Hard - Ages 11-12+) ────
  {
    question: 'What is an onomatopoeia?',
    answers: ['A word that sounds like what it describes', 'A type of poem', 'A figure of speech', 'A verb tense'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Think of words like "buzz" or "splash".',
    explanation: 'Onomatopoeia is when a word imitates the sound it describes, like buzz, meow, or crash.',
    tags: ['literary-devices', 'vocabulary'],
    source: 'manual-curation',
  },
  {
    question: 'What is a palindrome?',
    answers: ['A word that reads the same forwards and backwards', 'A type of rhyme', 'A long sentence', 'A foreign word'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Think of "racecar" or "noon".',
    explanation: 'A palindrome reads the same forwards and backwards, like "mom", "dad", or "racecar".',
    tags: ['word-play', 'patterns'],
    source: 'manual-curation',
  },
  {
    question: 'What does "etymology" mean?',
    answers: ['The study of word origins', 'The study of insects', 'The study of rocks', 'The study of plants'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s about where words come from.',
    explanation: 'Etymology is the study of the origin and history of words. (Note: entomology is the study of insects!)',
    tags: ['vocabulary', 'linguistics'],
    source: 'manual-curation',
  },
  {
    question: 'What is the past participle of "swim"?',
    answers: ['swum', 'swam', 'swimmed', 'swimming'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Used with "have" - "I have ___".',
    explanation: 'The past participle of swim is swum, as in "I have swum in the ocean."',
    tags: ['grammar', 'verbs'],
    source: 'manual-curation',
  },
  {
    question: 'What is the meaning of the idiom "break the ice"?',
    answers: ['To start a conversation', 'To break something', 'To make ice cubes', 'To go ice skating'],
    correctIndex: 0,
    category: 'language',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s about making people comfortable.',
    explanation: 'To "break the ice" means to initiate conversation or make people feel more comfortable in a social situation.',
    tags: ['idioms', 'expressions'],
    source: 'manual-curation',
  },

  // ──── Logic Questions (Easy - Ages 5-7) ────
  {
    question: 'What comes next: 1, 2, 3, 4, ...?',
    answers: ['5', '6', '10', '1'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Keep counting!',
    explanation: 'The pattern is counting: 1, 2, 3, 4, 5...',
    tags: ['patterns', 'counting'],
    source: 'manual-curation',
  },
  {
    question: 'If today is Monday, what day is tomorrow?',
    answers: ['Tuesday', 'Wednesday', 'Sunday', 'Monday'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'The day after Monday.',
    explanation: 'Tuesday comes after Monday.',
    tags: ['calendar', 'sequence'],
    source: 'manual-curation',
  },
  {
    question: 'Which one is different: dog, cat, car, bird?',
    answers: ['car', 'dog', 'cat', 'bird'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Three are animals!',
    explanation: 'Car is different because it\'s not a living animal.',
    tags: ['categorization', 'reasoning'],
    source: 'manual-curation',
  },
  {
    question: 'What shape has no corners?',
    answers: ['Circle', 'Triangle', 'Square', 'Rectangle'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Think round!',
    explanation: 'A circle has no corners or straight edges.',
    tags: ['shapes', 'observation'],
    source: 'manual-curation',
  },
  {
    question: 'If you have 2 apples and get 2 more, how many do you have?',
    answers: ['4', '3', '5', '2'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Add them together!',
    explanation: '2 + 2 = 4. You have 4 apples total.',
    tags: ['word-problems', 'addition'],
    source: 'manual-curation',
  },

  // ──── Logic Questions (Medium - Ages 8-10) ────
  {
    question: 'What number comes next: 5, 10, 15, 20, ...?',
    answers: ['25', '30', '24', '21'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Count by fives!',
    explanation: 'The pattern increases by 5 each time: 5, 10, 15, 20, 25...',
    tags: ['patterns', 'skip-counting'],
    source: 'manual-curation',
  },
  {
    question: 'All cats are animals. Fluffy is a cat. What is Fluffy?',
    answers: ['An animal', 'A dog', 'A bird', 'A plant'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Use logical reasoning!',
    explanation: 'If all cats are animals, and Fluffy is a cat, then Fluffy must be an animal.',
    tags: ['deduction', 'syllogism'],
    source: 'manual-curation',
  },
  {
    question: 'What letter comes next: A, C, E, G, ...?',
    answers: ['I', 'H', 'J', 'F'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Skip every other letter!',
    explanation: 'The pattern skips every other letter: A(skip B), C(skip D), E(skip F), G(skip H), I.',
    tags: ['patterns', 'alphabet'],
    source: 'manual-curation',
  },
  {
    question: 'If Anna is taller than Bob, and Bob is taller than Carl, who is the shortest?',
    answers: ['Carl', 'Bob', 'Anna', 'They are all the same height'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Think about the order!',
    explanation: 'Anna > Bob > Carl, so Carl is the shortest.',
    tags: ['reasoning', 'comparison'],
    source: 'manual-curation',
  },
  {
    question: 'A farmer has 12 chickens. All but 7 run away. How many are left?',
    answers: ['7', '5', '12', '0'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Read carefully: "all BUT 7".',
    explanation: '"All but 7" means 7 are left - the others ran away.',
    tags: ['word-problems', 'careful-reading'],
    source: 'manual-curation',
  },

  // ──── Logic Questions (Hard - Ages 11-12+) ────
  {
    question: 'I have cities but no houses, forests but no trees, and water but no fish. What am I?',
    answers: ['A map', 'A painting', 'A book', 'A dream'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It represents the world on paper.',
    explanation: 'A map shows cities, forests, and water, but doesn\'t contain the actual objects.',
    tags: ['riddles', 'lateral-thinking'],
    source: 'public-domain',
  },
  {
    question: 'If you rearrange the letters "CIFAIPC", you would have the name of a(n):',
    answers: ['Ocean', 'Country', 'City', 'Animal'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Think of water!',
    explanation: 'CIFAIPC rearranged spells PACIFIC - the Pacific Ocean.',
    tags: ['anagrams', 'geography'],
    source: 'manual-curation',
  },
  {
    question: 'What comes once in a minute, twice in a moment, but never in a thousand years?',
    answers: ['The letter M', 'Time', 'A second', 'The letter T'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Think about the letters in the words!',
    explanation: 'The letter M appears once in "minute", twice in "moment", and zero times in "thousand years".',
    tags: ['riddles', 'word-play'],
    source: 'public-domain',
  },
  {
    question: 'A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?',
    answers: ['$0.05', '$0.10', '$0.15', '$0.20'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Be careful! It\'s not $0.10.',
    explanation: 'Ball = $0.05, Bat = $1.05. The bat costs $1.00 MORE than the ball, and together they equal $1.10.',
    tags: ['math-logic', 'word-problems'],
    source: 'manual-curation',
  },
  {
    question: 'What is the next number in this sequence: 1, 1, 2, 3, 5, 8, ...?',
    answers: ['13', '11', '12', '10'],
    correctIndex: 0,
    category: 'logic',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Add the previous two numbers together!',
    explanation: 'This is the Fibonacci sequence: each number is the sum of the two before it. 5 + 8 = 13.',
    tags: ['patterns', 'fibonacci'],
    source: 'public-domain',
  },

  // ──── Geography Questions (Easy - Ages 5-7) ────
  {
    question: 'What is the largest ocean on Earth?',
    answers: ['Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It\'s between America and Asia!',
    explanation: 'The Pacific Ocean is the largest ocean, covering more than 30% of Earth\'s surface.',
    tags: ['oceans', 'earth'],
    source: 'public-domain',
  },
  {
    question: 'How many continents are there?',
    answers: ['7', '5', '6', '8'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'Count them: Africa, Antarctica, Asia...',
    explanation: 'There are 7 continents: Africa, Antarctica, Asia, Australia, Europe, North America, South America.',
    tags: ['continents', 'basics'],
    source: 'public-domain',
  },
  {
    question: 'What country is home to the kangaroo?',
    answers: ['Australia', 'Africa', 'China', 'Brazil'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It\'s a continent and a country!',
    explanation: 'Kangaroos are native to Australia.',
    tags: ['animals', 'countries'],
    source: 'public-domain',
  },
  {
    question: 'What is the tallest mountain in the world?',
    answers: ['Mount Everest', 'Mount Kilimanjaro', 'Mount Fuji', 'Rocky Mountains'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It\'s in the Himalayas!',
    explanation: 'Mount Everest is the tallest mountain at 29,032 feet (8,849 meters).',
    tags: ['mountains', 'records'],
    source: 'public-domain',
  },
  {
    question: 'What river is the longest in the world?',
    answers: ['Nile River', 'Amazon River', 'Mississippi River', 'Yangtze River'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It flows through Egypt!',
    explanation: 'The Nile River in Africa is generally considered the longest river at about 4,135 miles.',
    tags: ['rivers', 'africa'],
    source: 'public-domain',
  },

  // ──── Geography Questions (Medium - Ages 8-10) ────
  {
    question: 'What is the capital of France?',
    answers: ['Paris', 'London', 'Berlin', 'Rome'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'City of lights and the Eiffel Tower!',
    explanation: 'Paris is the capital and largest city of France.',
    tags: ['capitals', 'europe'],
    source: 'public-domain',
  },
  {
    question: 'Which desert is the largest hot desert in the world?',
    answers: ['Sahara Desert', 'Gobi Desert', 'Arabian Desert', 'Kalahari Desert'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It\'s in North Africa.',
    explanation: 'The Sahara Desert in Africa is the largest hot desert, covering about 9 million square kilometers.',
    tags: ['deserts', 'africa'],
    source: 'public-domain',
  },
  {
    question: 'What country has the most people?',
    answers: ['India', 'China', 'United States', 'Indonesia'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'As of 2024, it recently became #1!',
    explanation: 'India has the largest population as of 2024, with over 1.4 billion people.',
    tags: ['population', 'countries'],
    source: 'public-domain',
  },
  {
    question: 'Which country is shaped like a boot?',
    answers: ['Italy', 'Greece', 'Spain', 'Portugal'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'Home of pizza and pasta!',
    explanation: 'Italy is shaped like a boot, extending into the Mediterranean Sea.',
    tags: ['countries', 'shapes'],
    source: 'public-domain',
  },
  {
    question: 'What is the capital of Japan?',
    answers: ['Tokyo', 'Beijing', 'Seoul', 'Bangkok'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'One of the largest cities in the world!',
    explanation: 'Tokyo is the capital of Japan and one of the world\'s most populous metropolitan areas.',
    tags: ['capitals', 'asia'],
    source: 'public-domain',
  },

  // ──── Geography Questions (Hard - Ages 11-12+) ────
  {
    question: 'What is the smallest country in the world?',
    answers: ['Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s inside Rome, Italy!',
    explanation: 'Vatican City is the smallest country, at only 0.17 square miles (0.44 km²).',
    tags: ['countries', 'records'],
    source: 'public-domain',
  },
  {
    question: 'Which country has the most time zones?',
    answers: ['France', 'Russia', 'United States', 'China'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Including overseas territories!',
    explanation: 'France has 12 time zones due to its overseas territories across the world.',
    tags: ['time-zones', 'trivia'],
    source: 'public-domain',
  },
  {
    question: 'What imaginary line divides the Earth into Northern and Southern hemispheres?',
    answers: ['Equator', 'Prime Meridian', 'Tropic of Cancer', 'Arctic Circle'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s at 0° latitude.',
    explanation: 'The Equator is the imaginary line at 0° latitude that divides Earth into hemispheres.',
    tags: ['earth-science', 'coordinates'],
    source: 'public-domain',
  },
  {
    question: 'What sea is the lowest point on Earth\'s surface?',
    answers: ['Dead Sea', 'Red Sea', 'Black Sea', 'Caspian Sea'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s so salty you can float easily!',
    explanation: 'The Dead Sea is the lowest point on Earth at about 1,410 feet (430 meters) below sea level.',
    tags: ['water-bodies', 'records'],
    source: 'public-domain',
  },
  {
    question: 'What African country was never colonized by Europeans?',
    answers: ['Ethiopia', 'Kenya', 'Nigeria', 'South Africa'],
    correctIndex: 0,
    category: 'geography',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'One of the oldest countries in Africa.',
    explanation: 'Ethiopia (along with Liberia) was never colonized, maintaining independence through European colonization.',
    tags: ['africa', 'history'],
    source: 'public-domain',
  },

  // ──── Technology Questions (Easy - Ages 5-7) ────
  {
    question: 'What do you use a computer mouse for?',
    answers: ['Clicking and moving the cursor', 'Typing', 'Making sounds', 'Taking pictures'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'You move it on your desk!',
    explanation: 'A mouse controls the cursor on the screen and lets you click on things.',
    tags: ['computers', 'basics'],
    source: 'manual-curation',
  },
  {
    question: 'What does a keyboard help you do?',
    answers: ['Type letters and numbers', 'Draw pictures', 'Play music', 'Watch videos'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'It has lots of keys with letters!',
    explanation: 'A keyboard is used to type letters, numbers, and symbols into the computer.',
    tags: ['computers', 'input'],
    source: 'manual-curation',
  },
  {
    question: 'What shows you pictures and words on a computer?',
    answers: ['Monitor/Screen', 'Keyboard', 'Mouse', 'Printer'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'You look at it!',
    explanation: 'The monitor or screen displays images, text, and videos.',
    tags: ['computers', 'display'],
    source: 'manual-curation',
  },
  {
    question: 'What do you call a small computer you can carry in a bag?',
    answers: ['Laptop', 'Desktop', 'Phone', 'Tablet'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'You can use it on your lap!',
    explanation: 'A laptop is a portable computer you can carry and use anywhere.',
    tags: ['computers', 'devices'],
    source: 'manual-curation',
  },
  {
    question: 'What device do you use to make phone calls?',
    answers: ['Phone', 'Computer', 'TV', 'Camera'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'easy',
    ageBand: '5-7',
    hint: 'You talk into it!',
    explanation: 'A phone (or telephone) is used to make calls and send messages.',
    tags: ['devices', 'communication'],
    source: 'manual-curation',
  },

  // ──── Technology Questions (Medium - Ages 8-10) ────
  {
    question: 'What does "WWW" stand for in a website address?',
    answers: ['World Wide Web', 'Wide World Web', 'Web World Wide', 'World Web Wide'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'World... Wide... Web!',
    explanation: 'WWW stands for World Wide Web, the system of websites on the internet.',
    tags: ['internet', 'web'],
    source: 'public-domain',
  },
  {
    question: 'What do we call a harmful program that can damage your computer?',
    answers: ['Virus', 'Cookie', 'Browser', 'App'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It\'s like a disease for computers!',
    explanation: 'A computer virus is malicious software that can harm your system or data.',
    tags: ['cybersecurity', 'safety'],
    source: 'manual-curation',
  },
  {
    question: 'Who is often called the father of computers?',
    answers: ['Charles Babbage', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'He designed the first mechanical computer in the 1800s.',
    explanation: 'Charles Babbage designed the first mechanical computer (the Analytical Engine) in the 1830s.',
    tags: ['history', 'inventors'],
    source: 'public-domain',
  },
  {
    question: 'What does "USB" stand for?',
    answers: ['Universal Serial Bus', 'United States Bus', 'Universal System Bus', 'Unique Serial Bus'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'You plug things into USB ports!',
    explanation: 'USB stands for Universal Serial Bus - a standard for cables and connections.',
    tags: ['hardware', 'connections'],
    source: 'public-domain',
  },
  {
    question: 'What is the "brain" of the computer called?',
    answers: ['CPU (Central Processing Unit)', 'RAM', 'Hard Drive', 'Motherboard'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'medium',
    ageBand: '8-10',
    hint: 'It processes all the instructions!',
    explanation: 'The CPU (Central Processing Unit) is the main processor that executes program instructions.',
    tags: ['hardware', 'components'],
    source: 'public-domain',
  },

  // ──── Technology Questions (Hard - Ages 11-12+) ────
  {
    question: 'What does "HTML" stand for?',
    answers: ['HyperText Markup Language', 'High Tech Modern Language', 'Home Tool Markup Language', 'Hyperlink Text Markup Language'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s used to create web pages!',
    explanation: 'HTML (HyperText Markup Language) is the standard language for creating web pages.',
    tags: ['web-development', 'programming'],
    source: 'public-domain',
  },
  {
    question: 'Who invented the World Wide Web?',
    answers: ['Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'A British scientist at CERN.',
    explanation: 'Tim Berners-Lee invented the World Wide Web in 1989 while working at CERN.',
    tags: ['internet', 'history'],
    source: 'public-domain',
  },
  {
    question: 'What does "AI" stand for?',
    answers: ['Artificial Intelligence', 'Automated Information', 'Advanced Internet', 'Automatic Intelligence'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'Machines that can think!',
    explanation: 'AI (Artificial Intelligence) refers to machines or programs that can perform tasks requiring human intelligence.',
    tags: ['ai', 'future'],
    source: 'public-domain',
  },
  {
    question: 'How many bits are in a byte?',
    answers: ['8', '4', '16', '2'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'A byte is made up of this many bits.',
    explanation: 'A byte consists of 8 bits. A bit is the smallest unit of data (0 or 1).',
    tags: ['computing', 'data'],
    source: 'public-domain',
  },
  {
    question: 'What programming language is named after a type of coffee?',
    answers: ['Java', 'Python', 'Ruby', 'Swift'],
    correctIndex: 0,
    category: 'technology',
    difficulty: 'hard',
    ageBand: '11-12+',
    hint: 'It\'s a popular drink too!',
    explanation: 'Java is a programming language named after Java coffee, from the Indonesian island.',
    tags: ['programming', 'trivia'],
    source: 'public-domain',
  },
];

// ─── Conversion & Shard Generation ──────────────────────────

function convertToPackFormat(raw: RawQuizQuestion, index: number): QuizQuestionPack {
  const ageMetadata = createAgeMetadata(
    raw.ageBand === '5-7' ? 5 : raw.ageBand === '8-10' ? 8 : 11,
    raw.ageBand === '5-7' ? 7 : raw.ageBand === '8-10' ? 10 : null
  );

  const provenance = createProvenanceMetadata(
    raw.source,
    'CC0-1.0', // Public domain equivalent
    raw.sourceUrl,
    'content-pipeline-v1'
  );

  // Ensure correct answer is at index 0
  const reorderedAnswers = [...raw.answers];
  if (raw.correctIndex !== 0) {
    [reorderedAnswers[0], reorderedAnswers[raw.correctIndex]] =
      [reorderedAnswers[raw.correctIndex], reorderedAnswers[0]];
  }

  return {
    id: `q_${raw.category}_${raw.difficulty}_${String(index).padStart(3, '0')}`,
    category: raw.category,
    difficulty: raw.difficulty,
    ageMetadata,
    question: raw.question,
    answers: reorderedAnswers,
    hint: raw.hint,
    explanation: raw.explanation,
    rephraseHint: undefined,
    tags: raw.tags,
    provenance,
  };
}

function createShards(questions: QuizQuestionPack[]): QuizShard[] {
  const shards: QuizShard[] = [];

  for (let i = 0; i < questions.length; i += MAX_QUESTIONS_PER_SHARD) {
    const chunk = questions.slice(i, i + MAX_QUESTIONS_PER_SHARD);
    const shardNumber = Math.floor(i / MAX_QUESTIONS_PER_SHARD) + 1;

    shards.push({
      shardId: `quizzes-${String(shardNumber).padStart(3, '0')}`,
      schemaVersion: SCHEMA_VERSION,
      createdAt: new Date().toISOString(),
      questions: chunk,
    });
  }

  return shards;
}

// ─── Main Execution ──────────────────────────────────────────

function main() {
  console.log('🚀 Starting quiz content generation...');
  console.log(`📊 Processing ${CURATED_QUESTIONS.length} curated questions`);

  // Convert to pack format
  const packQuestions = CURATED_QUESTIONS.map((q, i) => convertToPackFormat(q, i));

  // Create shards
  const shards = createShards(packQuestions);

  // Ensure output directory exists
  const outputDir = path.join(__dirname, '../content/packs/default-v1/quizzes');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write shard files
  shards.forEach(shard => {
    const filename = `${shard.shardId}.json`;
    const filepath = path.join(outputDir, filename);
    fs.writeFileSync(filepath, JSON.stringify(shard, null, 2), 'utf-8');
    console.log(`✅ Written ${shard.questions.length} questions to ${filename}`);
  });

  // Generate statistics
  const stats = {
    totalQuestions: packQuestions.length,
    byCategory: {} as Record<string, number>,
    byDifficulty: {} as Record<string, number>,
    byAgeBand: {} as Record<string, number>,
  };

  packQuestions.forEach(q => {
    stats.byCategory[q.category] = (stats.byCategory[q.category] || 0) + 1;
    stats.byDifficulty[q.difficulty] = (stats.byDifficulty[q.difficulty] || 0) + 1;
    stats.byAgeBand[q.ageMetadata.ageBand] = (stats.byAgeBand[q.ageMetadata.ageBand] || 0) + 1;
  });

  console.log('\n📈 Generation Statistics:');
  console.log(`   Total: ${stats.totalQuestions} questions`);
  console.log(`   Categories: ${JSON.stringify(stats.byCategory, null, 2)}`);
  console.log(`   Difficulty: ${JSON.stringify(stats.byDifficulty, null, 2)}`);
  console.log(`   Age Bands: ${JSON.stringify(stats.byAgeBand, null, 2)}`);
  console.log(`\n✨ Content generation complete!`);
}

main();
