/**
 * scripts/content-pipeline/qa-report.ts
 * QA report generator — produces human-readable Markdown reports with
 * flagged items, statistics, and review checklists.
 * Issue #91 — Rephrasing + Quality Gate Pipeline
 *
 * TODO: DOC — report format, review workflow, approval process
 */

import * as fs from 'fs';
import * as path from 'path';
import type { QAReport, QAIssue, QASeverity, QACheckCategory } from './qa-checks';
import type { RephraseReport } from './rephrase';

// ─── Markdown Report Generator ───────────────────────────────

export function generateQAReportMarkdown(report: QAReport): string {
  const lines: string[] = [];

  lines.push('# 📋 Content QA Report');
  lines.push('');
  lines.push(`**Generated:** ${report.timestamp}`);
  lines.push(`**Status:** ${report.passed ? '✅ PASSED' : '❌ FAILED'}`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Quizzes checked | ${report.totalQuizzes} |`);
  lines.push(`| Articles checked | ${report.totalArticles} |`);
  lines.push(`| 🔴 Errors | ${report.errorCount} |`);
  lines.push(`| 🟡 Warnings | ${report.warningCount} |`);
  lines.push(`| 🔵 Info | ${report.infoCount} |`);
  lines.push(`| Items flagged for review | ${report.flaggedItemIds.length} |`);
  lines.push('');

  // Issues by category
  const byCategory = groupBy(report.issues, i => i.category);
  if (Object.keys(byCategory).length > 0) {
    lines.push('## Issues by Category');
    lines.push('');

    for (const [category, issues] of Object.entries(byCategory)) {
      const icon = getCategoryIcon(category as QACheckCategory);
      lines.push(`### ${icon} ${category} (${issues.length})`);
      lines.push('');

      for (const issue of issues) {
        const severity = getSeverityIcon(issue.severity);
        lines.push(`- ${severity} **${issue.itemId}** — ${issue.message}`);
        if (issue.suggestion) {
          lines.push(`  - 💡 ${issue.suggestion}`);
        }
        if (issue.fieldValue && issue.fieldValue.length < 100) {
          lines.push(`  - Value: \`${issue.fieldValue}\``);
        }
      }
      lines.push('');
    }
  }

  // Flagged items checklist
  if (report.flaggedItemIds.length > 0) {
    lines.push('## 📝 Review Checklist');
    lines.push('');
    lines.push('Items requiring human review before approval:');
    lines.push('');
    for (const id of report.flaggedItemIds) {
      const itemIssues = report.issues.filter(i => i.itemId === id && i.severity !== 'info');
      const severity = itemIssues.some(i => i.severity === 'error') ? '🔴' : '🟡';
      lines.push(`- [ ] ${severity} \`${id}\` — ${itemIssues.map(i => i.message).join('; ')}`);
    }
    lines.push('');
  }

  // Decision gate
  lines.push('## ✅ Approval Gate');
  lines.push('');
  if (report.passed) {
    lines.push('No blocking errors found. Content may proceed to publish after review of warnings.');
  } else {
    lines.push('**BLOCKED:** Content has errors that must be resolved before publishing.');
    lines.push('');
    lines.push('Resolve all 🔴 errors, then re-run the QA pipeline.');
  }
  lines.push('');
  lines.push('---');
  lines.push('*Generated by content-pipeline QA (Issue #91)*');

  return lines.join('\n');
}

// ─── Rephrase Report Generator ───────────────────────────────

export function generateRephraseReportMarkdown(report: RephraseReport): string {
  const lines: string[] = [];

  lines.push('# 🔄 Content Rephrase Report');
  lines.push('');
  lines.push(`**Generated:** ${report.timestamp}`);
  lines.push(`**Mode:** ${report.mode}`);
  lines.push(`**Target Age Band:** ${report.targetAgeBand}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Total items | ${report.totalItems} |`);
  lines.push(`| ✅ Rephrased | ${report.successCount} |`);
  lines.push(`| ⏭️ Skipped (already appropriate) | ${report.skippedCount} |`);
  lines.push(`| ❌ Failed | ${report.failedCount} |`);
  if (report.mode === 'live') {
    lines.push(`| LLM requests | ${report.llmStats.requestCount} |`);
    lines.push(`| Avg latency | ${report.llmStats.avgLatencyMs}ms |`);
  }
  lines.push('');

  // Readability changes
  const successful = report.results.filter(r => r.status === 'success');
  if (successful.length > 0) {
    lines.push('## Readability Changes');
    lines.push('');
    lines.push('| Item | Original Grade | Rephrased Grade | Target Band |');
    lines.push('|------|---------------|----------------|-------------|');
    for (const r of successful) {
      lines.push(`| ${r.itemId} | ${r.originalGradeLevel} | ${r.rephrasedGradeLevel} | ${r.targetAgeBand} |`);
    }
    lines.push('');
  }

  // Skipped items
  const skipped = report.results.filter(r => r.status === 'skipped');
  if (skipped.length > 0) {
    lines.push(`## Skipped Items (${skipped.length})`);
    lines.push('');
    lines.push('These items already meet the target readability level:');
    lines.push('');
    for (const r of skipped) {
      lines.push(`- ⏭️ \`${r.itemId}\` — grade ${r.originalGradeLevel} (target: ${r.targetAgeBand})`);
    }
    lines.push('');
  }

  // Failed items
  const failed = report.results.filter(r => r.status === 'failed');
  if (failed.length > 0) {
    lines.push(`## Failed Items (${failed.length})`);
    lines.push('');
    for (const r of failed) {
      lines.push(`- ❌ \`${r.itemId}\` — ${r.error}`);
    }
    lines.push('');
  }

  // Dry-run items
  const dryRunItems = report.results.filter(r => r.status === 'dry-run');
  if (dryRunItems.length > 0) {
    lines.push(`## Dry-Run Items (${dryRunItems.length})`);
    lines.push('');
    lines.push('These items would be sent to LLM for rephrasing in live mode:');
    lines.push('');
    for (const r of dryRunItems) {
      lines.push(`- 📝 \`${r.itemId}\` — grade ${r.originalGradeLevel} → target ${r.targetAgeBand}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by content-pipeline rephrase (Issue #91)*');

  return lines.join('\n');
}

// ─── File Output ─────────────────────────────────────────────

export function writeQAReport(
  report: QAReport,
  outputDir: string,
  format: 'markdown' | 'json' = 'markdown',
): string {
  const reportsDir = path.join(outputDir, 'qa-reports');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  if (format === 'json') {
    const filePath = path.join(reportsDir, `qa-report-${timestamp}.json`);
    fs.writeFileSync(filePath, JSON.stringify(report, null, 2));
    return filePath;
  }

  const filePath = path.join(reportsDir, `qa-report-${timestamp}.md`);
  const markdown = generateQAReportMarkdown(report);
  fs.writeFileSync(filePath, markdown);
  return filePath;
}

export function writeRephraseReport(
  report: RephraseReport,
  outputDir: string,
  format: 'markdown' | 'json' = 'markdown',
): string {
  const reportsDir = path.join(outputDir, 'qa-reports');
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  if (format === 'json') {
    const filePath = path.join(reportsDir, `rephrase-report-${timestamp}.json`);
    fs.writeFileSync(filePath, JSON.stringify(report, null, 2));
    return filePath;
  }

  const filePath = path.join(reportsDir, `rephrase-report-${timestamp}.md`);
  const markdown = generateRephraseReportMarkdown(report);
  fs.writeFileSync(filePath, markdown);
  return filePath;
}

// ─── Helpers ─────────────────────────────────────────────────

function groupBy<T>(items: T[], key: (item: T) => string): Record<string, T[]> {
  const groups: Record<string, T[]> = {};
  for (const item of items) {
    const k = key(item);
    if (!groups[k]) groups[k] = [];
    groups[k].push(item);
  }
  return groups;
}

function getSeverityIcon(severity: QASeverity): string {
  switch (severity) {
    case 'error': return '🔴';
    case 'warning': return '🟡';
    case 'info': return '🔵';
  }
}

function getCategoryIcon(category: QACheckCategory): string {
  switch (category) {
    case 'safety': return '🛡️';
    case 'readability': return '📖';
    case 'answer-consistency': return '✅';
    case 'length': return '📏';
    case 'age-appropriateness': return '👶';
    case 'completeness': return '📝';
    case 'duplicates': return '🔄';
  }
}
